# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/hardware_curriculum_design/nec_pl_zynq_vrlV0.1/build/gree_ir_pynq_axi/gree_ir_pynq_axi.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
# IP: The module: 'design_1_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/hardware_curriculum_design/nec_pl_zynq_vrlV0.1/build/gree_ir_pynq_axi/gree_ir_pynq_axi.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/hardware_curriculum_design/nec_pl_zynq_vrlV0.1/build/gree_ir_pynq_axi/gree_ir_pynq_axi.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/hardware_curriculum_design/nec_pl_zynq_vrlV0.1/build/gree_ir_pynq_axi/gree_ir_pynq_axi.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/hardware_curriculum_design/nec_pl_zynq_vrlV0.1/build/gree_ir_pynq_axi/gree_ir_pynq_axi.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
# IP: The module: 'design_1_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/hardware_curriculum_design/nec_pl_zynq_vrlV0.1/build/gree_ir_pynq_axi/gree_ir_pynq_axi.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/hardware_curriculum_design/nec_pl_zynq_vrlV0.1/build/gree_ir_pynq_axi/gree_ir_pynq_axi.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/hardware_curriculum_design/nec_pl_zynq_vrlV0.1/build/gree_ir_pynq_axi/gree_ir_pynq_axi.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
